POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "aa",
    "email": "aa@gmail.com",
    "password": "aa",
    "c_password": "aa"
}

### login

POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin1"
}

### perfil
GET http://127.0.0.1:8000/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|hIw80tgpKqlGknCmJVUty5rsX7pO1JeL75zo05DR


### perfil 2
GET http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|hIw80tgpKqlGknCmJVUty5rsX7pO1JeL75zo05DR


### logout
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|hIw80tgpKqlGknCmJVUty5rsX7pO1JeL75zo05DR
